
export EN_INSTANCE_REGION="EN_REGION"
export EN_APIKEY="EN_API_KEY"
export EN_INSTANCE_ID="EN_INSTANCE_ID"
export EN_IOS_DESTINATION_ID="EN_IOS_DESTINATION_ID"
export EN_ANDROID_DESTINATION_ID="EN_ANDROID_DESTINATION_ID"

export PUSH_INSTANCE_REGION="PUSH_INSTANCE_REGION"
export PUSH_INSTANCE_ID="PUSH_INSTANCE_ID"
export PUSH_APIKEY="PUSH_API_KEY"
export PUSH_CLIENT_SECRET="PUSH_CLIENT_SECRET"
